/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpCheckAll: typeof import('~icons/ep/check-all')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpCode: typeof import('~icons/ep/code')['default']
    IEpCrop: typeof import('~icons/ep/crop')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFolder: typeof import('~icons/ep/folder')['default']
    IEpImage: typeof import('~icons/ep/image')['default']
    IEpInfo: typeof import('~icons/ep/info')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IEpPicture: typeof import('~icons/ep/picture')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSelect: typeof import('~icons/ep/select')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpTickets: typeof import('~icons/ep/tickets')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
